services:
  qs-gui:
    volumes:
      - ${SSTDIR}:/usr/local/src/nsls-ii-sst
      - ${NBSDIR}:/usr/local/src/xraygui
      - ${BEAMLINE_PODS_DIR}/config/ipython:/usr/local/share/ipython
    command: >
      bash -c "
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/xraygui/nbs-core &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/xraygui/nbs-bl &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/xraygui/nbs-gui &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/nsls-ii-sst/sst_base &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/nsls-ii-sst/sst_tes &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/nsls-ii-sst/ucal &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/nsls-ii-sst/ucal_sim &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/nsls-ii-sst/sst-fasstcat &&
        nbs-gui --profile default
      " 
