services:
  qs-gui:
    volumes:
      - ${BEAMLINE_PODS_DIR}/config/ipython:/usr/local/share/ipython
      - ${HOME}/work/nsls-ii-sst:/usr/local/src/nsls-ii-sst
      - ${HOME}/work/xraygui:/usr/local/src/xraygui
      - ${HOME}/work/ophyd:/usr/local/src/ophyd

    command: >
      bash -c "
        conda install -y -c conda-forge qt-wayland &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/ophyd &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/nsls-ii-sst/bluesky-widgets &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/xraygui/nbs-core &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/xraygui/nbs-bl &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/xraygui/nbs-gui &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/nsls-ii-sst/sst_base &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/nsls-ii-sst/sst_tes &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/nsls-ii-sst/ucal &&
        pip3 install --no-deps --no-build-isolation -e /usr/local/src/nsls-ii-sst/ucal_sim &&
        nbs-gui --profile default
      " 
