[fasstcat]
_target = "sst_fasstcat.fasstcat.Fasstcat"
prefix = "XF:07ID1-ES{Fasstcat:"
name = "fasstcat"

[rbdTest]
_target = "sst_base.rbd9103.RBDFactory"
prefix = "XF:07ID1-ES{RBD9103:01}"
_group = "detectors"
name = "rbdTest"

[adr]
_target = "sst_base.sim.DummyObject"
prefix = "SIM_SST:adr"
name = "adr"
#long_name = "TES Cryostat"

[tes]
_target = "sst_tes.mca_tes.TESMCAFactory"
_group = "detectors"
name = "tes"
prefix = "SIM_SST:TES:"
mcaPrefix = "SIM_SST:tesmca:"
address = "tes-server"
path = "/data/raw"
setFilenamePattern = false
port = 4000

[i0]
_target = "sst_base.srs570.SRSADCFactory"
_group = "detectors"
_role = "intensity_detector"
srs_prefix = "XF:07ID-ES{SR570:01}SR1:"
prefix = "XF:07ID-BI[ADC:1-Ch:7]"
name = "ucal_i0up"

[i1]
_target = "sst_base.srs570.SRSADCFactory"
_group = "detectors"
_role = "indirect_alignment`"
srs_prefix = "XF:07ID-ES{SR570:02}SR1:"
prefix = "SIM_SST:i1:"
name = "ucal_i1"

[ref]
_target = "sst_base.detectors.scalar.ADCBuffer"
_group = "detectors"
prefix = "SIM_SST:ref:"
name = "ucal_ref"

[sc]
_target = "sst_base.detectors.scalar.ADCBuffer"
_group = "detectors"
prefix = "SIM_SST:sc:"
name = "ucal_sc"
#long_name = "Sample Drain Current"

#[wps1]
#_target = "sst_base.wienerPS.WienerPSFactory"
#prefix = "XF:07ID-ES{WPS:01"
#name = "wps1"
#_group = ["motors"]
#lvch0 = "PEY-Grid"
#lvch1 = "DuoA-Grid"
#lvch2 = "DuoB-Grid"
#lvch3 = "LAR1-Grid"
#hvch0 = "PEY-Col"
#hvch1 = "PEY-BE"
#hvch2 = "DuoA-Col"
#hvch3 = "DuoA-BE"
#hvch4 = "DuoB-Col"
#hvch5 = "DuoB-BE"
#hvch6 = "LAR1-MCP"
#hvch7 = "LAR1-Phos"

[en]
_target = "sst_base.energy.EnPosFactory"
_group = "source"
_load_order = 2
prefix = ""
#long_name = "SST Energy"
name = "en"

[gv26]
_target = "sst_base.sim.DummyObject"
_group = "gatevalves"
prefix = "XF:07IDB-VA:2{Mir:M3C-GV:1}"
name = "gv26"
#long_name = "Post Shutter Gate Valve"
openval = 1
closeval = 0
shutter_type = "GV"

[gv27]
_target = "sst_base.sim.DummyObject"
_group = "gatevalves"
prefix = "XF:07IDB-VA:3{Slt:C-GV:1}"
name= "gv27"
#long_name = "Upstream Gate Valve"
openval = 1
closeval = 0
shutter_type = "GV"

[gv28]
_target = "sst_base.sim.DummyObject"
_group = "gatevalves"
prefix = "XF:07IDB-VA:2{BT:1-GV:1}"
name = "gv28"
#long_name = "Downstream Gate Valve"
openval = 1
closeval = 0
shutter_type = "GV"

[mir4]
_target = "sst_base.mirrors.FMBHexapodMirror"
_group = "mirrors"
prefix = "XF:07ID2-OP{Mir:M4CD"
name = "mir4"
#long_name = "SST 1 Mirror 4 fmb"

[mir3]
_target = "sst_base.mirrors.FMBHexapodMirror"
_group = "mirrors"
prefix = "XF:07ID1-OP{Mir:M3ABC"
name = "mir3"
#long_name = "SST 1 Mirror 3 fmb"

[mir1]
_target = "sst_base.mirrors.FMBHexapodMirror"
_group = "motors"
prefix = "XF:07IDA-OP{Mir:M1"
name = "mir1"
#long_name = "SST 1 Mirror 1 fmb"

[Exit_Slit]
_target = "sst_base.motors.PrettyMotor"
_group = ["motors", "apertures"]
_role = "slits"
prefix = "SIM_SST:eslit:"
name = "eslit"
#long_name = "Exit Slit of Mono Vertical Gap"


[i0upAu]
_target = "sst_base.motors.PrettyMotor"
_group = "motors"
prefix = "SIM_SST:i0upAu:"
name = "i0upAu"

[tesz]
_target = "sst_base.motors.PrettyMotor"
_group = "motors"
prefix = "XF:07ID1-BI{UCAL-Ax:DetX}"
name = "tesz"

[manipulator]
_target = "sst_base.manipulator.ManipulatorBuilder"
_group = "manipulators"
_role = "primary_sampleholder"
prefix = "XF:07ID1-BI{NXFS-Ax:"
name = "manip"

[multimesh]
_target = "ucal.multimesh.MultiMeshBuilder"
_group = "manipulators"
_role = "reference_sampleholder"
prefix = "XF:07ID1-BI{I0Up-Ax:"
name = "i0upmultimesh"
#long_name = "SST Reference Mesh Ladder"

[psh1]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"	
prefix = "SIM_SST:psh1:"
name = "psh1"
#long_name = "Front-End Shutter"
shutter_type = "FE"
openval = 0
closeval = 1

[psh4]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
prefix = "SIM_SST:psh4:"
name = "psh4"
#long_name = "Hutch Photon Shutter"
openval = 0
closeval = 1

[psh10]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
prefix = "SIM_SST:psh10:"
name = "psh10"
#long_name = "Upstream Photon Shutter"
openval = 0
closeval = 1

[psh7]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
_role = "default_shutter"
shutter_type = "PH"
prefix = "SIM_SST:psh7:"
name = "psh7"
#long_name = "Downstream Photon Shutter"
openval = 0
closeval = 1

[ring_current]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
_role = "beam_current"
prefix = "SIM_SST:current"
name = "ring_current"
#long_name = "NSLS-II Ring Current"

[ring_status]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
_role = "beam_status"
prefix = "SIM_SST:status"
name = "NSLS-II Status"

[sst_control]
_target = "ophyd.EpicsSignal"
_group = "signals"
prefix = "SIM_SST:Endstn-Sel"
name = "Endstation in Control"
string = true


[manipx]
_alias = "manipulator.x"
_group = 'motors'

[manipy]
_alias = "manipulator.y"
_group = 'motors'

[manipz]
_alias = "manipulator.z"
_group = 'motors'

[manipr]
_alias = "manipulator.r"
_group = 'motors'

[samplex]
_alias = "manipulator.sx"
_group = 'motors'

[sampley]
_alias = "manipulator.sy"
_group = 'motors'

[samplez]
_alias = "manipulator.sz"
_group = 'motors'

[sampler]
_alias = "manipulator.sr"
_group = 'motors'

[energy]
_alias = "en.energy"
_group = 'motors'
_load_order = 2
_role = "energy"

[polarization]
_alias = "en.polarization"
_group = 'motors'
_load_order = 2
_role = "polarization"

[eslit]
_alias = "Exit_Slit"
