[gui]
header = "nbs-gui-header"

[gui.tabs]
include = ["nbs-gui-queue", "nbs-gui-console", "kafka-table-tab", "nbs-gui-monitor", "sst-gui-samples", "ucal-tes-tab", "sst-gui-testing"]

[gui.plans]
include = [
    "nbs-gui-scan",
    "nbs-gui-move", 
    "nbs-gui-xas",
    "nbs-gui-timescan",
    "nbs-gui-varscan",
    "sst-gui-energy-flyscan",
    "nbs-gui-flyscan",
    "ucal-tes-cal",
    "ucal-tes-setup",
    "manual-sample-move"
]

[models.beamline]
primary_energy = "en"
primary_manipulator = "manipulator"
loader = "nbs_bl.qt.models.beamline.SSTBeamlineModel"

[devices]
psh1 = { visible = false, view_only = true }
psh4 = { visible = false }
Exit_Slit = { label = "Exit Slit" }
en = {"_role" = "energy", "load_order" = 1}
tes = { "_group" = "misc" }

[loaders]
"EnPosFactory" = "sst_base.qt.models.energy.SST1EnergyModel"
"I400SingleCh" = "nbs_gui.models.ScalarModel"
"PrettyMotorFMBO" = "nbs_gui.models.MotorModel"
"PrettyMotor" = "nbs_gui.models.MotorModel"
"PrettyMotorFMBODeadband" = "nbs_gui.models.MotorModel"
"PrettyMotorFMBODeadbandFlyer" = "nbs_gui.models.MotorModel"
"FMBHexapodMirror" = "nbs_gui.models.MotorTupleModel"
"EpicsSignalRO" = "nbs_gui.models.PVModel"
"EpicsSignal" = "nbs_gui.models.PVModel"
"ShutterSet" = "nbs_gui.models.GVModel"
"EPS_Shutter" = "nbs_gui.models.GVModel"
"ManipulatorBuilder" = "nbs_gui.models.PseudoPositionerModel"
"ophScalar" = "nbs_gui.models.ScalarModel"
"ADCBuffer" = "nbs_gui.models.ScalarModel"
"SRSADCFactory" = "sst_base.qt.models.srs570.SRS570Model"
"RBDFactory" = "sst_base.qt.models.rbd9103.RBD9103Model"
"EpicsMotor" = "nbs_gui.models.MotorModel"
"MultiMeshBuilder" = "nbs_gui.models.PseudoPositionerModel"
"QuadSlits" = "sst_base.qt.models.quadSlits.QuadSlitsModel"
"FMBOQuadSlits" = "sst_base.qt.models.quadSlits.QuadSlitsModel"
"TESMCAFactory" = "ucal.qt.models.tesModel.TESModel"
"WienerPSFactory" = "nbs_gui.models.MotorTupleModel"
"Fasstcat" = "sst_base.qt.models.fasstcat.FasstcatModel"

[kafka]
config_file = "/etc/bluesky/kafka.yml"
bl_acronym = "nbs"