[loaders]
"PrettyMotor" = "nbs_sim.devices.motors.FakeMotor"
"EpicsMotor" = "nbs_sim.devices.motors.FakeMotor"
"DeadbandEpicsMotor" = "nbs_sim.devices.motors.FakeMotor"
"FlyableMotor" = "nbs_sim.devices.motors.FakeMotor"
"PrettyMotorFMBO" = "nbs_sim.devices.motors.FakeFMBOMotor"
"PrettyMotorFMBODeadband" = "nbs_sim.devices.motors.FakeFMBOMotor"
"PrettyMotorFMBODeadbandFlyer" = "nbs_sim.devices.motors.FakeFMBOMotor"
"ADCBuffer" = "nbs_sim.devices.detectors.ADCVoltage"
"ophScalar" = "nbs_sim.devices.detectors.GenericDetector"
"EPS_Shutter" = "nbs_sim.devices.shutters.SSTShutter"
"MultiMeshBuilder" = "nbs_sim.devices.manipulator.MultiMesh"
"ManipulatorBuilder" = "nbs_sim.devices.manipulator.Manipulator"
"EnPosFactory" = "nbs_sim.devices.energy.SST1Energy"
"FMBOQuadSlits" = "nbs_sim.devices.slits.FMBOQuadSlits"
"QuadSlits" = "nbs_sim.devices.slits.QuadSlits"
"FMBHexapodMirror" = "nbs_sim.devices.mirrors.FMBHexapodMirror"
"HexapodMirror" = "nbs_sim.devices.mirrors.FMBHexapodMirror"
"EpicsSignalRO" = "nbs_sim.devices.signals.ConstantSignal"
"EpicsSignal" = "nbs_sim.devices.signals.ConstantSignal"
"ShutterWait" = "nbs_sim.devices.signals.ConstantSignal"
"EpicsMCABase" = "nbs_sim.devices.caproto_mca.MCASIM"
"WienerPSFactory" = "nbs_sim.devices.wiener_ps.WienerPS"
"Fasstcat" = "nbs_sim.devices.fasstcat.FasstcatSimDevice"
"SRSADCFactory" = "nbs_sim.devices.srs570.SRSADCFactory"
"RBDFactory" = "nbs_sim.devices.rbd9103.RBD9103"

[devices]
Exit_Slit = {_target = "nbs_sim.devices.slits.Slit", trans_min = 0, trans_max = 40, _group="apertures", _role="slits", user_limits=[0, 40]}
ring_current = {_target = "nbs_sim.devices.signals.RingCurrent"}
i0 = {kind="i0"}
rbdTest = {kind="i0"}
i1 = {kind="i1"}
ref = {kind="ref"}
en = {_role="energy", _load_order=1 }
tes = {_target = "nbs_sim.devices.caproto_mca.MCASIM", _group = "detectors", name = "tes_mca", prefix = "SIM_SST:tesmca:"}

